apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0xya
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-0xya@sha256:29614902df0340baa37dad871d16c83a2fb0a1ab84564aa6f62b9133362dde6f
        name: my-nodejs
        resources: {}
status: {}
