apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0xya
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0xya
    app.kubernetes.io/part-of: tkrw-pr712-0075-0024-app
  name: devfile-sample-0xya
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0xya
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0xya
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-0xya@sha256:29614902df0340baa37dad871d16c83a2fb0a1ab84564aa6f62b9133362dde6f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
